name: deep_orientation
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports_abc=0.5=py_1
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py27_0
  - cffi=1.13.2=py27h2e261b9_0
  - cloudpickle=1.2.2=py_1
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py27h516909a_0
  - dask-core=1.2.2=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - dill=0.3.1.1=py27_0
  - enum34=1.1.6=py27_1002
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.9.1=h8a8886c_1
  - funcsigs=1.0.2=py27_0
  - functools32=3.2.3.2=py_3
  - futures=3.3.0=py27_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_1
  - glib=2.58.3=py27h6f030ca_1002
  - gmp=6.2.0=he1b5a44_1
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.5=h0935bb2_1
  - gstreamer=1.14.5=h36ae1b5_1
  - h5py=2.10.0=nompi_py27h513d04c_101
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - imageio=2.6.1=py27_0
  - intel-openmp=2019.4=243
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py27hc9558a2_0
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.1=default_hde54327_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_mkl
  - liblapacke=3.8.0=14_mkl
  - libllvm9=9.0.1=hc9558a2_0
  - libopencv=4.2.0=py27_2
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.3=h8b12597_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.10=hee79883_0
  - linecache2=1.0.0=py27_0
  - llvmlite=0.31.0=py27hd408876_0
  - matplotlib-base=2.2.4=py27h250f245_2
  - mkl=2019.4=243
  - mkl-service=2.3.0=py27he904b0f_0
  - mkl_fft=1.0.15=py27ha843d7b_0
  - mkl_random=1.1.0=py27hd6b4f25_0
  - multiprocess=0.70.9=py27h516909a_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.2=py_1
  - ninja=1.9.0=py27hfd86e86_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numba=0.47.0=py27h962f231_0
  - numpy=1.16.6=py27hbc911f0_0
  - numpy-base=1.16.6=py27hde5b4d6_0
  - olefile=0.46=py_0
  - opencv=4.2.0=py27_2
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1d=h516909a_0
  - pandas=0.24.2=py27he6710b0_0
  - pathos=0.2.5=py_0
  - pcre=8.43=he1b5a44_0
  - pillow=6.2.1=py27h34e0f95_0
  - pip=19.3.1=py27_0
  - pixman=0.38.0=h516909a_1003
  - pox=0.2.7=py_0
  - ppft=1.6.6.1=py27_0
  - protobuf=3.11.3=py27he1b5a44_0
  - pthread-stubs=0.4=h14c3975_1001
  - py-opencv=4.2.0=py27h5ca1d4c_2
  - pycparser=2.19=py_0
  - pyparsing=2.4.6=py_0
  - python=2.7.17=h9bab390_0
  - python-dateutil=2.8.1=py_0
  - pytorch=1.0.1=cuda100py27he554f03_0
  - pytz=2019.3=py_0
  - pywavelets=1.0.3=py27hd352d35_1
  - pyyaml=5.2=py27h7b6447c_0
  - qt=5.12.5=hd8c4c69_1
  - quaternion=2019.12.11.22.25.52=py27hc1659b7_0
  - readline=7.0=h7b6447c_5
  - scikit-image=0.14.3=py27hb3f55d8_0
  - scipy=1.2.1=py27h7c811a0_0
  - setuptools=44.0.0=py27_0
  - singledispatch=3.4.0.3=py27_1000
  - six=1.13.0=py27_0
  - sqlite=3.31.1=h7b6447c_0
  - subprocess32=3.5.4=py27h516909a_0
  - tensorboardx=1.8=py_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - torchvision=0.2.1=py27_0
  - tornado=5.1.1=py27h14c3975_1000
  - traceback2=1.4.0=py27_0
  - unittest2=1.1.0=py27_0
  - wheel=0.33.6=py27_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h96e3832_1
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
